"""
SmolAgents tools for equation evaluation and code execution.
This module provides @tool-decorated functions for the agent workflow.
"""
from __future__ import annotations

import numpy as np
import torch
from typing import Any, Dict, Optional
from smolagents import tool

from llmsr import code_manipulation


@tool
def evaluate_equation_code(
    equation_code: str,
    dataset: Dict[str, Any],
    function_name: str = "equation",
    max_params: int = 10,
    use_torch: bool = False
) -> float:
    """
    Evaluates a generated equation function against a dataset.
    This tool executes the equation code, optimizes parameters, and returns a fitness score.
    
    Args:
        equation_code: The Python code defining the equation function body
        dataset: Dictionary with 'inputs' and 'outputs' arrays
        function_name: Name of the equation function (default: 'equation')
        max_params: Maximum number of parameters to optimize
        use_torch: Whether to use PyTorch tensors
        
    Returns:
        Negative MSE loss as fitness score (higher is better), or -inf if execution fails
    """
    try:
        # Extract inputs and outputs
        inputs = dataset['inputs']
        outputs = dataset['outputs']
        
        # Build the complete function code
        if use_torch:
            imports = "import torch\nimport numpy as np\n"
        else:
            imports = "import numpy as np\n"
        
        # Create the function wrapper
        full_code = f"{imports}\ndef {function_name}(*args, **kwargs):\n"
        
        # Indent the equation code
        for line in equation_code.strip().split('\n'):
            full_code += f"    {line}\n"
        
        # Execute the code to define the function
        namespace = {}
        exec(full_code, namespace)
        equation_func = namespace[function_name]
        
        # Prepare optimization
        if use_torch:
            from scipy.optimize import minimize
            
            def loss(params):
                params_tensor = torch.tensor(params, dtype=torch.float32)
                # Extract input columns based on function signature
                if inputs.shape[1] == 2:
                    x, v = inputs[:, 0], inputs[:, 1]
                    y_pred = equation_func(x, v, params_tensor)
                elif inputs.shape[1] == 3:
                    x, v, t = inputs[:, 0], inputs[:, 1], inputs[:, 2]
                    y_pred = equation_func(t, x, v, params_tensor)
                else:
                    # General case: pass all columns
                    y_pred = equation_func(*[inputs[:, i] for i in range(inputs.shape[1])], params_tensor)
                
                mse = torch.mean((y_pred - outputs) ** 2)
                return mse.item()
        else:
            from scipy.optimize import minimize
            
            def loss(params):
                # Extract input columns based on dataset structure
                if inputs.shape[1] == 2:
                    x, v = inputs[:, 0], inputs[:, 1]
                    y_pred = equation_func(x, v, params)
                elif inputs.shape[1] == 3:
                    # Could be (t, x, v) or (strain, temp, other)
                    col0, col1, col2 = inputs[:, 0], inputs[:, 1], inputs[:, 2]
                    y_pred = equation_func(col0, col1, col2, params)
                elif inputs.shape[1] == 4:
                    # E.g., bacterial growth: (b, s, temp, pH)
                    y_pred = equation_func(*[inputs[:, i] for i in range(4)], params)
                else:
                    # Fallback: pass all columns
                    y_pred = equation_func(*[inputs[:, i] for i in range(inputs.shape[1])], params)
                
                return np.mean((y_pred - outputs) ** 2)
        
        # Optimize parameters
        initial_params = [1.0] * max_params
        result = minimize(loss, initial_params, method='BFGS')
        
        # Return negative loss (higher is better)
        final_loss = result.fun
        
        if np.isnan(final_loss) or np.isinf(final_loss):
            return float('-inf')
        
        return -final_loss
    
    except Exception as e:
        print(f"Evaluation error: {e}")
        return float('-inf')


@tool
def extract_function_body(generated_text: str) -> str:
    """
    Extracts the function body from LLM-generated text.
    Removes function signature and leading descriptions.
    
    Args:
        generated_text: Raw text generated by the LLM
        
    Returns:
        Cleaned function body with proper indentation
    """
    lines = generated_text.splitlines()
    func_body_lineno = 0
    find_def = False
    
    for lineno, line in enumerate(lines):
        if line.strip().startswith('def '):
            func_body_lineno = lineno
            find_def = True
            break
    
    if find_def:
        # Extract body (skip the def line)
        code = ''
        indent = '    '
        for line in lines[func_body_lineno + 1:]:
            # Ensure proper indentation
            if line and not line.startswith(indent):
                line = indent + line
            code += line + '\n'
        return code.strip()
    
    # If no def found, return the original text
    return generated_text.strip()


@tool  
def validate_equation_syntax(equation_code: str) -> bool:
    """
    Validates that the equation code has correct Python syntax.
    
    Args:
        equation_code: Python code to validate
        
    Returns:
        True if syntax is valid, False otherwise
    """
    try:
        # Try to compile the code
        import ast
        # Wrap in a function to make it valid
        wrapped = f"def temp_func():\n"
        for line in equation_code.strip().split('\n'):
            wrapped += f"    {line}\n"
        
        ast.parse(wrapped)
        return True
    except SyntaxError:
        return False

